"""initial db

Revision ID: b0fceafd5fa8
Revises: 
Create Date: 2026-03-25 20:57:37.619721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'b0fceafd5fa8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriasExperimentos',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('EstadosExperimentos',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Roles',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Usuarios',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('NombreCompleto', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=True),
    sa.Column('UsaProveedor', sa.Boolean(), nullable=False),
    sa.Column('Habilitado', sa.Boolean(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('FechaModificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Proyectos',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=False),
    sa.Column('UsuarioId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Habilitado', sa.Boolean(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('FechaModificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('UsuarioRol',
    sa.Column('UsuarioId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('RolId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['RolId'], ['Roles.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('UsuarioId', 'RolId')
    )
    op.create_table('Experimentos',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=False),
    sa.Column('Habilitado', sa.Boolean(), nullable=False),
    sa.Column('CategoriaExperimentoId', sa.Integer(), nullable=False),
    sa.Column('EstadoExperimentoId', sa.Integer(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('FechaModificacion', sa.DateTime(), nullable=True),
    sa.Column('ProyectoId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['CategoriaExperimentoId'], ['CategoriasExperimentos.Id'], ),
    sa.ForeignKeyConstraint(['EstadoExperimentoId'], ['EstadosExperimentos.Id'], ),
    sa.ForeignKeyConstraint(['ProyectoId'], ['Proyectos.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Anotaciones',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Contenido', sa.Text(), nullable=False),
    sa.Column('Habilitado', sa.Boolean(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('FechaModificacion', sa.DateTime(), nullable=True),
    sa.Column('UsuarioId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('ExperimentoId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['ExperimentoId'], ['Experimentos.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ComentarioExperimento',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Comentario', sa.Text(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('ExperimentoId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('UsuarioId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['ExperimentoId'], ['Experimentos.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ArchivosAdjuntos',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('UrlBlob', sa.Text(), nullable=False),
    sa.Column('AnotacionId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('FechaModificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AnotacionId'], ['Anotaciones.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ComentarioAnotacion',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('Comentario', sa.Text(), nullable=False),
    sa.Column('FechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('AnotacionId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('UsuarioId', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['AnotacionId'], ['Anotaciones.Id'], ),
    sa.ForeignKeyConstraint(['UsuarioId'], ['Usuarios.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ComentarioAnotacion')
    op.drop_table('ArchivosAdjuntos')
    op.drop_table('ComentarioExperimento')
    op.drop_table('Anotaciones')
    op.drop_table('Experimentos')
    op.drop_table('UsuarioRol')
    op.drop_table('Proyectos')
    op.drop_table('Usuarios')
    op.drop_table('Roles')
    op.drop_table('EstadosExperimentos')
    op.drop_table('CategoriasExperimentos')
    # ### end Alembic commands ###
